/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV2KposBalancesGetPost200Response,
  ApiV2KposBalancesGetPostRequest,
  ApiV2KposRefillPost200Response,
  ApiV2KposRefillPostRequest,
} from '../models';
import {
    ApiV2KposBalancesGetPost200ResponseFromJSON,
    ApiV2KposBalancesGetPost200ResponseToJSON,
    ApiV2KposBalancesGetPostRequestFromJSON,
    ApiV2KposBalancesGetPostRequestToJSON,
    ApiV2KposRefillPost200ResponseFromJSON,
    ApiV2KposRefillPost200ResponseToJSON,
    ApiV2KposRefillPostRequestFromJSON,
    ApiV2KposRefillPostRequestToJSON,
} from '../models';

export interface ApiV2KposBalancesGetPostOperationRequest {
    apiV2KposBalancesGetPostRequest: ApiV2KposBalancesGetPostRequest;
}

export interface ApiV2KposRefillPostOperationRequest {
    apiV2KposRefillPostRequest: ApiV2KposRefillPostRequest;
}

/**
 * KPOSApi - interface
 * 
 * @export
 * @interface KPOSApiInterface
 */
export interface KPOSApiInterface {
    /**
     * Returns KPOS balances
     * @summary KPOS balances
     * @param {ApiV2KposBalancesGetPostRequest} apiV2KposBalancesGetPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KPOSApiInterface
     */
    apiV2KposBalancesGetPostRaw(requestParameters: ApiV2KposBalancesGetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2KposBalancesGetPost200Response>>;

    /**
     * Returns KPOS balances
     * KPOS balances
     */
    apiV2KposBalancesGetPost(requestParameters: ApiV2KposBalancesGetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2KposBalancesGetPost200Response>;

    /**
     * Refills KPOS reserve
     * @summary KPOS refill
     * @param {ApiV2KposRefillPostRequest} apiV2KposRefillPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KPOSApiInterface
     */
    apiV2KposRefillPostRaw(requestParameters: ApiV2KposRefillPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2KposRefillPost200Response>>;

    /**
     * Refills KPOS reserve
     * KPOS refill
     */
    apiV2KposRefillPost(requestParameters: ApiV2KposRefillPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2KposRefillPost200Response>;

}

/**
 * 
 */
export class KPOSApi extends runtime.BaseAPI implements KPOSApiInterface {

    /**
     * Returns KPOS balances
     * KPOS balances
     */
    async apiV2KposBalancesGetPostRaw(requestParameters: ApiV2KposBalancesGetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2KposBalancesGetPost200Response>> {
        if (requestParameters.apiV2KposBalancesGetPostRequest === null || requestParameters.apiV2KposBalancesGetPostRequest === undefined) {
            throw new runtime.RequiredError('apiV2KposBalancesGetPostRequest','Required parameter requestParameters.apiV2KposBalancesGetPostRequest was null or undefined when calling apiV2KposBalancesGetPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-sig"] = this.configuration.apiKey("api-sig"); // SignatureAuth authentication
        }

        const response = await this.request({
            path: `/api/v2/kpos/balances/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV2KposBalancesGetPostRequestToJSON(requestParameters.apiV2KposBalancesGetPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV2KposBalancesGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns KPOS balances
     * KPOS balances
     */
    async apiV2KposBalancesGetPost(requestParameters: ApiV2KposBalancesGetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2KposBalancesGetPost200Response> {
        const response = await this.apiV2KposBalancesGetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refills KPOS reserve
     * KPOS refill
     */
    async apiV2KposRefillPostRaw(requestParameters: ApiV2KposRefillPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2KposRefillPost200Response>> {
        if (requestParameters.apiV2KposRefillPostRequest === null || requestParameters.apiV2KposRefillPostRequest === undefined) {
            throw new runtime.RequiredError('apiV2KposRefillPostRequest','Required parameter requestParameters.apiV2KposRefillPostRequest was null or undefined when calling apiV2KposRefillPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-sig"] = this.configuration.apiKey("api-sig"); // SignatureAuth authentication
        }

        const response = await this.request({
            path: `/api/v2/kpos/refill`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV2KposRefillPostRequestToJSON(requestParameters.apiV2KposRefillPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV2KposRefillPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Refills KPOS reserve
     * KPOS refill
     */
    async apiV2KposRefillPost(requestParameters: ApiV2KposRefillPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2KposRefillPost200Response> {
        const response = await this.apiV2KposRefillPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
