/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV2WalletListPost200Response,
  ApiV2WalletListPostRequest,
} from '../models';
import {
    ApiV2WalletListPost200ResponseFromJSON,
    ApiV2WalletListPost200ResponseToJSON,
    ApiV2WalletListPostRequestFromJSON,
    ApiV2WalletListPostRequestToJSON,
} from '../models';

export interface ApiV2WalletListPostOperationRequest {
    apiV2WalletListPostRequest: ApiV2WalletListPostRequest;
}

/**
 * WalletApi - interface
 * 
 * @export
 * @interface WalletApiInterface
 */
export interface WalletApiInterface {
    /**
     * Returns wallet balances for all assets held by the user.
     * @summary Wallet balances
     * @param {ApiV2WalletListPostRequest} apiV2WalletListPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    apiV2WalletListPostRaw(requestParameters: ApiV2WalletListPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2WalletListPost200Response>>;

    /**
     * Returns wallet balances for all assets held by the user.
     * Wallet balances
     */
    apiV2WalletListPost(requestParameters: ApiV2WalletListPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2WalletListPost200Response>;

}

/**
 * 
 */
export class WalletApi extends runtime.BaseAPI implements WalletApiInterface {

    /**
     * Returns wallet balances for all assets held by the user.
     * Wallet balances
     */
    async apiV2WalletListPostRaw(requestParameters: ApiV2WalletListPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV2WalletListPost200Response>> {
        if (requestParameters.apiV2WalletListPostRequest === null || requestParameters.apiV2WalletListPostRequest === undefined) {
            throw new runtime.RequiredError('apiV2WalletListPostRequest','Required parameter requestParameters.apiV2WalletListPostRequest was null or undefined when calling apiV2WalletListPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-sig"] = this.configuration.apiKey("api-sig"); // SignatureAuth authentication
        }

        const response = await this.request({
            path: `/api/v2/wallet/list`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV2WalletListPostRequestToJSON(requestParameters.apiV2WalletListPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV2WalletListPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns wallet balances for all assets held by the user.
     * Wallet balances
     */
    async apiV2WalletListPost(requestParameters: ApiV2WalletListPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV2WalletListPost200Response> {
        const response = await this.apiV2WalletListPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
