/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAdminMarketTransactionsListPostRequest
 */
export interface ApiAdminMarketTransactionsListPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAdminMarketTransactionsListPostRequest
     */
    userId: ApiAdminMarketTransactionsListPostRequestUserIdEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAdminMarketTransactionsListPostRequest
     */
    fromDate?: ApiAdminMarketTransactionsListPostRequestFromDateEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAdminMarketTransactionsListPostRequest
     */
    toDate?: ApiAdminMarketTransactionsListPostRequestToDateEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ApiAdminMarketTransactionsListPostRequest
     */
    distinctUsers?: boolean;
}


/**
 * @export
 */
export const ApiAdminMarketTransactionsListPostRequestUserIdEnum = {
    Ok: 'ok'
} as const;
export type ApiAdminMarketTransactionsListPostRequestUserIdEnum = typeof ApiAdminMarketTransactionsListPostRequestUserIdEnum[keyof typeof ApiAdminMarketTransactionsListPostRequestUserIdEnum];

/**
 * @export
 */
export const ApiAdminMarketTransactionsListPostRequestFromDateEnum = {
    Ok: 'ok'
} as const;
export type ApiAdminMarketTransactionsListPostRequestFromDateEnum = typeof ApiAdminMarketTransactionsListPostRequestFromDateEnum[keyof typeof ApiAdminMarketTransactionsListPostRequestFromDateEnum];

/**
 * @export
 */
export const ApiAdminMarketTransactionsListPostRequestToDateEnum = {
    Ok: 'ok'
} as const;
export type ApiAdminMarketTransactionsListPostRequestToDateEnum = typeof ApiAdminMarketTransactionsListPostRequestToDateEnum[keyof typeof ApiAdminMarketTransactionsListPostRequestToDateEnum];


/**
 * Check if a given object implements the ApiAdminMarketTransactionsListPostRequest interface.
 */
export function instanceOfApiAdminMarketTransactionsListPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ApiAdminMarketTransactionsListPostRequestFromJSON(json: any): ApiAdminMarketTransactionsListPostRequest {
    return ApiAdminMarketTransactionsListPostRequestFromJSONTyped(json, false);
}

export function ApiAdminMarketTransactionsListPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAdminMarketTransactionsListPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'fromDate': !exists(json, 'fromDate') ? undefined : json['fromDate'],
        'toDate': !exists(json, 'toDate') ? undefined : json['toDate'],
        'distinctUsers': !exists(json, 'distinctUsers') ? undefined : json['distinctUsers'],
    };
}

export function ApiAdminMarketTransactionsListPostRequestToJSON(value?: ApiAdminMarketTransactionsListPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'fromDate': value.fromDate,
        'toDate': value.toDate,
        'distinctUsers': value.distinctUsers,
    };
}

