/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiAdminMarketTickerAddPost200ResponseOneOf,
    instanceOfApiAdminMarketTickerAddPost200ResponseOneOf,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSON,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped,
    ApiAdminMarketTickerAddPost200ResponseOneOfToJSON,
} from './ApiAdminMarketTickerAddPost200ResponseOneOf';
import {
    ApiAdminMarketTickerAddPost200ResponseOneOf1,
    instanceOfApiAdminMarketTickerAddPost200ResponseOneOf1,
    ApiAdminMarketTickerAddPost200ResponseOneOf1FromJSON,
    ApiAdminMarketTickerAddPost200ResponseOneOf1FromJSONTyped,
    ApiAdminMarketTickerAddPost200ResponseOneOf1ToJSON,
} from './ApiAdminMarketTickerAddPost200ResponseOneOf1';
import {
    ApiAdminMarketTickerAddPost200ResponseOneOf2,
    instanceOfApiAdminMarketTickerAddPost200ResponseOneOf2,
    ApiAdminMarketTickerAddPost200ResponseOneOf2FromJSON,
    ApiAdminMarketTickerAddPost200ResponseOneOf2FromJSONTyped,
    ApiAdminMarketTickerAddPost200ResponseOneOf2ToJSON,
} from './ApiAdminMarketTickerAddPost200ResponseOneOf2';

/**
 * @type ApiAdminMarketTickerAddPost200Response
 * 
 * @export
 */
export type ApiAdminMarketTickerAddPost200Response = ApiAdminMarketTickerAddPost200ResponseOneOf | ApiAdminMarketTickerAddPost200ResponseOneOf1 | ApiAdminMarketTickerAddPost200ResponseOneOf2;

export function ApiAdminMarketTickerAddPost200ResponseFromJSON(json: any): ApiAdminMarketTickerAddPost200Response {
    return ApiAdminMarketTickerAddPost200ResponseFromJSONTyped(json, false);
}

export function ApiAdminMarketTickerAddPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAdminMarketTickerAddPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped(json, true), ...ApiAdminMarketTickerAddPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiAdminMarketTickerAddPost200ResponseOneOf2FromJSONTyped(json, true) };
}

export function ApiAdminMarketTickerAddPost200ResponseToJSON(value?: ApiAdminMarketTickerAddPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiAdminMarketTickerAddPost200ResponseOneOf(value)) {
        return ApiAdminMarketTickerAddPost200ResponseOneOfToJSON(value as ApiAdminMarketTickerAddPost200ResponseOneOf);
    }
    if (instanceOfApiAdminMarketTickerAddPost200ResponseOneOf1(value)) {
        return ApiAdminMarketTickerAddPost200ResponseOneOf1ToJSON(value as ApiAdminMarketTickerAddPost200ResponseOneOf1);
    }
    if (instanceOfApiAdminMarketTickerAddPost200ResponseOneOf2(value)) {
        return ApiAdminMarketTickerAddPost200ResponseOneOf2ToJSON(value as ApiAdminMarketTickerAddPost200ResponseOneOf2);
    }

    return {};
}

