/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiAdminMarketTickerAddPost200ResponseOneOf,
    instanceOfApiAdminMarketTickerAddPost200ResponseOneOf,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSON,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped,
    ApiAdminMarketTickerAddPost200ResponseOneOfToJSON,
} from './ApiAdminMarketTickerAddPost200ResponseOneOf';
import {
    ApiAdminMarketTickerRemovePost200ResponseOneOf,
    instanceOfApiAdminMarketTickerRemovePost200ResponseOneOf,
    ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSON,
    ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSONTyped,
    ApiAdminMarketTickerRemovePost200ResponseOneOfToJSON,
} from './ApiAdminMarketTickerRemovePost200ResponseOneOf';

/**
 * @type ApiAdminMarketTickerRemovePost200Response
 * 
 * @export
 */
export type ApiAdminMarketTickerRemovePost200Response = ApiAdminMarketTickerAddPost200ResponseOneOf | ApiAdminMarketTickerRemovePost200ResponseOneOf;

export function ApiAdminMarketTickerRemovePost200ResponseFromJSON(json: any): ApiAdminMarketTickerRemovePost200Response {
    return ApiAdminMarketTickerRemovePost200ResponseFromJSONTyped(json, false);
}

export function ApiAdminMarketTickerRemovePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAdminMarketTickerRemovePost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped(json, true), ...ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSONTyped(json, true) };
}

export function ApiAdminMarketTickerRemovePost200ResponseToJSON(value?: ApiAdminMarketTickerRemovePost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiAdminMarketTickerAddPost200ResponseOneOf(value)) {
        return ApiAdminMarketTickerAddPost200ResponseOneOfToJSON(value as ApiAdminMarketTickerAddPost200ResponseOneOf);
    }
    if (instanceOfApiAdminMarketTickerRemovePost200ResponseOneOf(value)) {
        return ApiAdminMarketTickerRemovePost200ResponseOneOfToJSON(value as ApiAdminMarketTickerRemovePost200ResponseOneOf);
    }

    return {};
}

