/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Market does not exist
 * @export
 * @interface ApiAdminMarketTickerRemovePost200ResponseOneOf
 */
export interface ApiAdminMarketTickerRemovePost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiAdminMarketTickerRemovePost200ResponseOneOf
     */
    result: ApiAdminMarketTickerRemovePost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiAdminMarketTickerRemovePost200ResponseOneOf
     */
    code: ApiAdminMarketTickerRemovePost200ResponseOneOfCodeEnum;
}


/**
 * @export
 */
export const ApiAdminMarketTickerRemovePost200ResponseOneOfResultEnum = {
    Fail: 'fail'
} as const;
export type ApiAdminMarketTickerRemovePost200ResponseOneOfResultEnum = typeof ApiAdminMarketTickerRemovePost200ResponseOneOfResultEnum[keyof typeof ApiAdminMarketTickerRemovePost200ResponseOneOfResultEnum];

/**
 * @export
 */
export const ApiAdminMarketTickerRemovePost200ResponseOneOfCodeEnum = {
    NUMBER_9000: 9000
} as const;
export type ApiAdminMarketTickerRemovePost200ResponseOneOfCodeEnum = typeof ApiAdminMarketTickerRemovePost200ResponseOneOfCodeEnum[keyof typeof ApiAdminMarketTickerRemovePost200ResponseOneOfCodeEnum];


/**
 * Check if a given object implements the ApiAdminMarketTickerRemovePost200ResponseOneOf interface.
 */
export function instanceOfApiAdminMarketTickerRemovePost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSON(json: any): ApiAdminMarketTickerRemovePost200ResponseOneOf {
    return ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiAdminMarketTickerRemovePost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAdminMarketTickerRemovePost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'code': json['code'],
    };
}

export function ApiAdminMarketTickerRemovePost200ResponseOneOfToJSON(value?: ApiAdminMarketTickerRemovePost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'code': value.code,
    };
}

