/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiFcmSendPostRequestMessage } from './ApiFcmSendPostRequestMessage';
import {
    ApiFcmSendPostRequestMessageFromJSON,
    ApiFcmSendPostRequestMessageFromJSONTyped,
    ApiFcmSendPostRequestMessageToJSON,
} from './ApiFcmSendPostRequestMessage';

/**
 * 
 * @export
 * @interface ApiFcmSendPostRequest
 */
export interface ApiFcmSendPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiFcmSendPostRequest
     */
    recipient: ApiFcmSendPostRequestRecipientEnum;
    /**
     * 
     * @type {ApiFcmSendPostRequestMessage}
     * @memberof ApiFcmSendPostRequest
     */
    message: ApiFcmSendPostRequestMessage;
    /**
     * 
     * @type {string}
     * @memberof ApiFcmSendPostRequest
     */
    app: ApiFcmSendPostRequestAppEnum;
}


/**
 * @export
 */
export const ApiFcmSendPostRequestRecipientEnum = {
    Ok: 'ok'
} as const;
export type ApiFcmSendPostRequestRecipientEnum = typeof ApiFcmSendPostRequestRecipientEnum[keyof typeof ApiFcmSendPostRequestRecipientEnum];

/**
 * @export
 */
export const ApiFcmSendPostRequestAppEnum = {
    Ok: 'ok'
} as const;
export type ApiFcmSendPostRequestAppEnum = typeof ApiFcmSendPostRequestAppEnum[keyof typeof ApiFcmSendPostRequestAppEnum];


/**
 * Check if a given object implements the ApiFcmSendPostRequest interface.
 */
export function instanceOfApiFcmSendPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "recipient" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "app" in value;

    return isInstance;
}

export function ApiFcmSendPostRequestFromJSON(json: any): ApiFcmSendPostRequest {
    return ApiFcmSendPostRequestFromJSONTyped(json, false);
}

export function ApiFcmSendPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFcmSendPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'message': ApiFcmSendPostRequestMessageFromJSON(json['message']),
        'app': json['app'],
    };
}

export function ApiFcmSendPostRequestToJSON(value?: ApiFcmSendPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recipient': value.recipient,
        'message': ApiFcmSendPostRequestMessageToJSON(value.message),
        'app': value.app,
    };
}

