/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiAdminMarketTickerAddPost200ResponseOneOf,
    instanceOfApiAdminMarketTickerAddPost200ResponseOneOf,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSON,
    ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped,
    ApiAdminMarketTickerAddPost200ResponseOneOfToJSON,
} from './ApiAdminMarketTickerAddPost200ResponseOneOf';
import {
    ApiFcmSendPost200ResponseOneOf,
    instanceOfApiFcmSendPost200ResponseOneOf,
    ApiFcmSendPost200ResponseOneOfFromJSON,
    ApiFcmSendPost200ResponseOneOfFromJSONTyped,
    ApiFcmSendPost200ResponseOneOfToJSON,
} from './ApiFcmSendPost200ResponseOneOf';

/**
 * @type ApiFcmSendPost200Response
 * 
 * @export
 */
export type ApiFcmSendPost200Response = ApiAdminMarketTickerAddPost200ResponseOneOf | ApiFcmSendPost200ResponseOneOf;

export function ApiFcmSendPost200ResponseFromJSON(json: any): ApiFcmSendPost200Response {
    return ApiFcmSendPost200ResponseFromJSONTyped(json, false);
}

export function ApiFcmSendPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFcmSendPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiAdminMarketTickerAddPost200ResponseOneOfFromJSONTyped(json, true), ...ApiFcmSendPost200ResponseOneOfFromJSONTyped(json, true) };
}

export function ApiFcmSendPost200ResponseToJSON(value?: ApiFcmSendPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiAdminMarketTickerAddPost200ResponseOneOf(value)) {
        return ApiAdminMarketTickerAddPost200ResponseOneOfToJSON(value as ApiAdminMarketTickerAddPost200ResponseOneOf);
    }
    if (instanceOfApiFcmSendPost200ResponseOneOf(value)) {
        return ApiFcmSendPost200ResponseOneOfToJSON(value as ApiFcmSendPost200ResponseOneOf);
    }

    return {};
}

