/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiFcmSendPostRequestMessage
 */
export interface ApiFcmSendPostRequestMessage {
    /**
     * 
     * @type {string}
     * @memberof ApiFcmSendPostRequestMessage
     */
    title: ApiFcmSendPostRequestMessageTitleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiFcmSendPostRequestMessage
     */
    content: ApiFcmSendPostRequestMessageContentEnum;
}


/**
 * @export
 */
export const ApiFcmSendPostRequestMessageTitleEnum = {
    Ok: 'ok'
} as const;
export type ApiFcmSendPostRequestMessageTitleEnum = typeof ApiFcmSendPostRequestMessageTitleEnum[keyof typeof ApiFcmSendPostRequestMessageTitleEnum];

/**
 * @export
 */
export const ApiFcmSendPostRequestMessageContentEnum = {
    Ok: 'ok'
} as const;
export type ApiFcmSendPostRequestMessageContentEnum = typeof ApiFcmSendPostRequestMessageContentEnum[keyof typeof ApiFcmSendPostRequestMessageContentEnum];


/**
 * Check if a given object implements the ApiFcmSendPostRequestMessage interface.
 */
export function instanceOfApiFcmSendPostRequestMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function ApiFcmSendPostRequestMessageFromJSON(json: any): ApiFcmSendPostRequestMessage {
    return ApiFcmSendPostRequestMessageFromJSONTyped(json, false);
}

export function ApiFcmSendPostRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFcmSendPostRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function ApiFcmSendPostRequestMessageToJSON(value?: ApiFcmSendPostRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
    };
}

