/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiMarketTickerListPost200ResponseItemsInner
 */
export interface ApiMarketTickerListPost200ResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    id: ApiMarketTickerListPost200ResponseItemsInnerIdEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    price?: ApiMarketTickerListPost200ResponseItemsInnerPriceEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    change?: ApiMarketTickerListPost200ResponseItemsInnerChangeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    changeQuantity?: ApiMarketTickerListPost200ResponseItemsInnerChangeQuantityEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    buyingCurrency: ApiMarketTickerListPost200ResponseItemsInnerBuyingCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200ResponseItemsInner
     */
    payingCurrency: ApiMarketTickerListPost200ResponseItemsInnerPayingCurrencyEnum;
}


/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerIdEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerIdEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerIdEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerIdEnum];

/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerPriceEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerPriceEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerPriceEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerPriceEnum];

/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerChangeEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerChangeEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerChangeEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerChangeEnum];

/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerChangeQuantityEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerChangeQuantityEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerChangeQuantityEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerChangeQuantityEnum];

/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerBuyingCurrencyEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerBuyingCurrencyEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerBuyingCurrencyEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerBuyingCurrencyEnum];

/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseItemsInnerPayingCurrencyEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseItemsInnerPayingCurrencyEnum = typeof ApiMarketTickerListPost200ResponseItemsInnerPayingCurrencyEnum[keyof typeof ApiMarketTickerListPost200ResponseItemsInnerPayingCurrencyEnum];


/**
 * Check if a given object implements the ApiMarketTickerListPost200ResponseItemsInner interface.
 */
export function instanceOfApiMarketTickerListPost200ResponseItemsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "buyingCurrency" in value;
    isInstance = isInstance && "payingCurrency" in value;

    return isInstance;
}

export function ApiMarketTickerListPost200ResponseItemsInnerFromJSON(json: any): ApiMarketTickerListPost200ResponseItemsInner {
    return ApiMarketTickerListPost200ResponseItemsInnerFromJSONTyped(json, false);
}

export function ApiMarketTickerListPost200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketTickerListPost200ResponseItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'change': !exists(json, 'change') ? undefined : json['change'],
        'changeQuantity': !exists(json, 'changeQuantity') ? undefined : json['changeQuantity'],
        'buyingCurrency': json['buyingCurrency'],
        'payingCurrency': json['payingCurrency'],
    };
}

export function ApiMarketTickerListPost200ResponseItemsInnerToJSON(value?: ApiMarketTickerListPost200ResponseItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
        'change': value.change,
        'changeQuantity': value.changeQuantity,
        'buyingCurrency': value.buyingCurrency,
        'payingCurrency': value.payingCurrency,
    };
}

