/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiMarketsPost200ResponseItemsInner
 */
export interface ApiMarketsPost200ResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    buyingCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    payingCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    minAmount: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    mainMarket: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    pricePrecision: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    available?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    opening?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    ecoOpening?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    lastPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    change?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    volume?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    bidsAvailableSince: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200ResponseItemsInner
     */
    asksAvailableSince: string;
}

/**
 * Check if a given object implements the ApiMarketsPost200ResponseItemsInner interface.
 */
export function instanceOfApiMarketsPost200ResponseItemsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "buyingCurrency" in value;
    isInstance = isInstance && "payingCurrency" in value;
    isInstance = isInstance && "minAmount" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "mainMarket" in value;
    isInstance = isInstance && "pricePrecision" in value;
    isInstance = isInstance && "index" in value;
    isInstance = isInstance && "bidsAvailableSince" in value;
    isInstance = isInstance && "asksAvailableSince" in value;

    return isInstance;
}

export function ApiMarketsPost200ResponseItemsInnerFromJSON(json: any): ApiMarketsPost200ResponseItemsInner {
    return ApiMarketsPost200ResponseItemsInnerFromJSONTyped(json, false);
}

export function ApiMarketsPost200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketsPost200ResponseItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'buyingCurrency': json['buyingCurrency'],
        'payingCurrency': json['payingCurrency'],
        'minAmount': json['minAmount'],
        'type': json['type'],
        'mainMarket': json['mainMarket'],
        'pricePrecision': json['pricePrecision'],
        'index': json['index'],
        'available': !exists(json, 'available') ? undefined : json['available'],
        'opening': !exists(json, 'opening') ? undefined : json['opening'],
        'ecoOpening': !exists(json, 'ecoOpening') ? undefined : json['ecoOpening'],
        'lastPrice': !exists(json, 'lastPrice') ? undefined : json['lastPrice'],
        'change': !exists(json, 'change') ? undefined : json['change'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'bidsAvailableSince': json['bidsAvailableSince'],
        'asksAvailableSince': json['asksAvailableSince'],
    };
}

export function ApiMarketsPost200ResponseItemsInnerToJSON(value?: ApiMarketsPost200ResponseItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'buyingCurrency': value.buyingCurrency,
        'payingCurrency': value.payingCurrency,
        'minAmount': value.minAmount,
        'type': value.type,
        'mainMarket': value.mainMarket,
        'pricePrecision': value.pricePrecision,
        'index': value.index,
        'available': value.available,
        'opening': value.opening,
        'ecoOpening': value.ecoOpening,
        'lastPrice': value.lastPrice,
        'change': value.change,
        'volume': value.volume,
        'bidsAvailableSince': value.bidsAvailableSince,
        'asksAvailableSince': value.asksAvailableSince,
    };
}

