/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiMarketTickerListPost200ResponseItemsInner } from './ApiMarketTickerListPost200ResponseItemsInner';
import {
    ApiMarketTickerListPost200ResponseItemsInnerFromJSON,
    ApiMarketTickerListPost200ResponseItemsInnerFromJSONTyped,
    ApiMarketTickerListPost200ResponseItemsInnerToJSON,
} from './ApiMarketTickerListPost200ResponseItemsInner';

/**
 * 
 * @export
 * @interface ApiMarketTickerListPost200Response
 */
export interface ApiMarketTickerListPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiMarketTickerListPost200Response
     */
    result: ApiMarketTickerListPost200ResponseResultEnum;
    /**
     * 
     * @type {Array<ApiMarketTickerListPost200ResponseItemsInner>}
     * @memberof ApiMarketTickerListPost200Response
     */
    items: Array<ApiMarketTickerListPost200ResponseItemsInner>;
}


/**
 * @export
 */
export const ApiMarketTickerListPost200ResponseResultEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketTickerListPost200ResponseResultEnum = typeof ApiMarketTickerListPost200ResponseResultEnum[keyof typeof ApiMarketTickerListPost200ResponseResultEnum];


/**
 * Check if a given object implements the ApiMarketTickerListPost200Response interface.
 */
export function instanceOfApiMarketTickerListPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function ApiMarketTickerListPost200ResponseFromJSON(json: any): ApiMarketTickerListPost200Response {
    return ApiMarketTickerListPost200ResponseFromJSONTyped(json, false);
}

export function ApiMarketTickerListPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketTickerListPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'items': ((json['items'] as Array<any>).map(ApiMarketTickerListPost200ResponseItemsInnerFromJSON)),
    };
}

export function ApiMarketTickerListPost200ResponseToJSON(value?: ApiMarketTickerListPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'items': ((value.items as Array<any>).map(ApiMarketTickerListPost200ResponseItemsInnerToJSON)),
    };
}

