/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiMarketChangesListPost200ResponseItemsInner } from './ApiMarketChangesListPost200ResponseItemsInner';
import {
    ApiMarketChangesListPost200ResponseItemsInnerFromJSON,
    ApiMarketChangesListPost200ResponseItemsInnerFromJSONTyped,
    ApiMarketChangesListPost200ResponseItemsInnerToJSON,
} from './ApiMarketChangesListPost200ResponseItemsInner';

/**
 * 
 * @export
 * @interface ApiMarketChangesListPost200Response
 */
export interface ApiMarketChangesListPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiMarketChangesListPost200Response
     */
    result: ApiMarketChangesListPost200ResponseResultEnum;
    /**
     * 
     * @type {Array<ApiMarketChangesListPost200ResponseItemsInner>}
     * @memberof ApiMarketChangesListPost200Response
     */
    items: Array<ApiMarketChangesListPost200ResponseItemsInner>;
}


/**
 * @export
 */
export const ApiMarketChangesListPost200ResponseResultEnum = {
    Ok: 'ok'
} as const;
export type ApiMarketChangesListPost200ResponseResultEnum = typeof ApiMarketChangesListPost200ResponseResultEnum[keyof typeof ApiMarketChangesListPost200ResponseResultEnum];


/**
 * Check if a given object implements the ApiMarketChangesListPost200Response interface.
 */
export function instanceOfApiMarketChangesListPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function ApiMarketChangesListPost200ResponseFromJSON(json: any): ApiMarketChangesListPost200Response {
    return ApiMarketChangesListPost200ResponseFromJSONTyped(json, false);
}

export function ApiMarketChangesListPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketChangesListPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'items': ((json['items'] as Array<any>).map(ApiMarketChangesListPost200ResponseItemsInnerFromJSON)),
    };
}

export function ApiMarketChangesListPost200ResponseToJSON(value?: ApiMarketChangesListPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'items': ((value.items as Array<any>).map(ApiMarketChangesListPost200ResponseItemsInnerToJSON)),
    };
}

