/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiUserMarketTransactionsListPost200ResponseListInner } from './ApiUserMarketTransactionsListPost200ResponseListInner';
import {
    ApiUserMarketTransactionsListPost200ResponseListInnerFromJSON,
    ApiUserMarketTransactionsListPost200ResponseListInnerFromJSONTyped,
    ApiUserMarketTransactionsListPost200ResponseListInnerToJSON,
} from './ApiUserMarketTransactionsListPost200ResponseListInner';

/**
 * 
 * @export
 * @interface ApiUserMarketTransactionsListPost200Response
 */
export interface ApiUserMarketTransactionsListPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiUserMarketTransactionsListPost200Response
     */
    result: ApiUserMarketTransactionsListPost200ResponseResultEnum;
    /**
     * 
     * @type {Array<ApiUserMarketTransactionsListPost200ResponseListInner>}
     * @memberof ApiUserMarketTransactionsListPost200Response
     */
    list: Array<ApiUserMarketTransactionsListPost200ResponseListInner>;
}


/**
 * @export
 */
export const ApiUserMarketTransactionsListPost200ResponseResultEnum = {
    Ok: 'ok'
} as const;
export type ApiUserMarketTransactionsListPost200ResponseResultEnum = typeof ApiUserMarketTransactionsListPost200ResponseResultEnum[keyof typeof ApiUserMarketTransactionsListPost200ResponseResultEnum];


/**
 * Check if a given object implements the ApiUserMarketTransactionsListPost200Response interface.
 */
export function instanceOfApiUserMarketTransactionsListPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "list" in value;

    return isInstance;
}

export function ApiUserMarketTransactionsListPost200ResponseFromJSON(json: any): ApiUserMarketTransactionsListPost200Response {
    return ApiUserMarketTransactionsListPost200ResponseFromJSONTyped(json, false);
}

export function ApiUserMarketTransactionsListPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserMarketTransactionsListPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'list': ((json['list'] as Array<any>).map(ApiUserMarketTransactionsListPost200ResponseListInnerFromJSON)),
    };
}

export function ApiUserMarketTransactionsListPost200ResponseToJSON(value?: ApiUserMarketTransactionsListPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'list': ((value.list as Array<any>).map(ApiUserMarketTransactionsListPost200ResponseListInnerToJSON)),
    };
}

