/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUserFcmTokenRegisterPostRequest
 */
export interface ApiUserFcmTokenRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUserFcmTokenRegisterPostRequest
     */
    fcmToken: ApiUserFcmTokenRegisterPostRequestFcmTokenEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiUserFcmTokenRegisterPostRequest
     */
    app: ApiUserFcmTokenRegisterPostRequestAppEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiUserFcmTokenRegisterPostRequest
     */
    deviceToken: ApiUserFcmTokenRegisterPostRequestDeviceTokenEnum;
}


/**
 * @export
 */
export const ApiUserFcmTokenRegisterPostRequestFcmTokenEnum = {
    Fail: 'fail'
} as const;
export type ApiUserFcmTokenRegisterPostRequestFcmTokenEnum = typeof ApiUserFcmTokenRegisterPostRequestFcmTokenEnum[keyof typeof ApiUserFcmTokenRegisterPostRequestFcmTokenEnum];

/**
 * @export
 */
export const ApiUserFcmTokenRegisterPostRequestAppEnum = {
    Fail: 'fail'
} as const;
export type ApiUserFcmTokenRegisterPostRequestAppEnum = typeof ApiUserFcmTokenRegisterPostRequestAppEnum[keyof typeof ApiUserFcmTokenRegisterPostRequestAppEnum];

/**
 * @export
 */
export const ApiUserFcmTokenRegisterPostRequestDeviceTokenEnum = {
    Fail: 'fail'
} as const;
export type ApiUserFcmTokenRegisterPostRequestDeviceTokenEnum = typeof ApiUserFcmTokenRegisterPostRequestDeviceTokenEnum[keyof typeof ApiUserFcmTokenRegisterPostRequestDeviceTokenEnum];


/**
 * Check if a given object implements the ApiUserFcmTokenRegisterPostRequest interface.
 */
export function instanceOfApiUserFcmTokenRegisterPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fcmToken" in value;
    isInstance = isInstance && "app" in value;
    isInstance = isInstance && "deviceToken" in value;

    return isInstance;
}

export function ApiUserFcmTokenRegisterPostRequestFromJSON(json: any): ApiUserFcmTokenRegisterPostRequest {
    return ApiUserFcmTokenRegisterPostRequestFromJSONTyped(json, false);
}

export function ApiUserFcmTokenRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserFcmTokenRegisterPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fcmToken': json['fcmToken'],
        'app': json['app'],
        'deviceToken': json['deviceToken'],
    };
}

export function ApiUserFcmTokenRegisterPostRequestToJSON(value?: ApiUserFcmTokenRegisterPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fcmToken': value.fcmToken,
        'app': value.app,
        'deviceToken': value.deviceToken,
    };
}

