/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * No app found
 * @export
 * @interface ApiUserFcmTokenRegisterPost200ResponseOneOf
 */
export interface ApiUserFcmTokenRegisterPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiUserFcmTokenRegisterPost200ResponseOneOf
     */
    result: ApiUserFcmTokenRegisterPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiUserFcmTokenRegisterPost200ResponseOneOf
     */
    code: ApiUserFcmTokenRegisterPost200ResponseOneOfCodeEnum;
}


/**
 * @export
 */
export const ApiUserFcmTokenRegisterPost200ResponseOneOfResultEnum = {
    Fail: 'fail'
} as const;
export type ApiUserFcmTokenRegisterPost200ResponseOneOfResultEnum = typeof ApiUserFcmTokenRegisterPost200ResponseOneOfResultEnum[keyof typeof ApiUserFcmTokenRegisterPost200ResponseOneOfResultEnum];

/**
 * @export
 */
export const ApiUserFcmTokenRegisterPost200ResponseOneOfCodeEnum = {
    NUMBER_9000: 9000
} as const;
export type ApiUserFcmTokenRegisterPost200ResponseOneOfCodeEnum = typeof ApiUserFcmTokenRegisterPost200ResponseOneOfCodeEnum[keyof typeof ApiUserFcmTokenRegisterPost200ResponseOneOfCodeEnum];


/**
 * Check if a given object implements the ApiUserFcmTokenRegisterPost200ResponseOneOf interface.
 */
export function instanceOfApiUserFcmTokenRegisterPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ApiUserFcmTokenRegisterPost200ResponseOneOfFromJSON(json: any): ApiUserFcmTokenRegisterPost200ResponseOneOf {
    return ApiUserFcmTokenRegisterPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiUserFcmTokenRegisterPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserFcmTokenRegisterPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'code': json['code'],
    };
}

export function ApiUserFcmTokenRegisterPost200ResponseOneOfToJSON(value?: ApiUserFcmTokenRegisterPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'code': value.code,
    };
}

