/* tslint:disable */
/* eslint-disable */
/**
 * Kanga.exchange API
 * This is API generated from kanga.exchange code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUserMarketTransactionsListPostRequest
 */
export interface ApiUserMarketTransactionsListPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUserMarketTransactionsListPostRequest
     */
    fromDate?: ApiUserMarketTransactionsListPostRequestFromDateEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiUserMarketTransactionsListPostRequest
     */
    toDate?: ApiUserMarketTransactionsListPostRequestToDateEnum;
}


/**
 * @export
 */
export const ApiUserMarketTransactionsListPostRequestFromDateEnum = {
    Ok: 'ok'
} as const;
export type ApiUserMarketTransactionsListPostRequestFromDateEnum = typeof ApiUserMarketTransactionsListPostRequestFromDateEnum[keyof typeof ApiUserMarketTransactionsListPostRequestFromDateEnum];

/**
 * @export
 */
export const ApiUserMarketTransactionsListPostRequestToDateEnum = {
    Ok: 'ok'
} as const;
export type ApiUserMarketTransactionsListPostRequestToDateEnum = typeof ApiUserMarketTransactionsListPostRequestToDateEnum[keyof typeof ApiUserMarketTransactionsListPostRequestToDateEnum];


/**
 * Check if a given object implements the ApiUserMarketTransactionsListPostRequest interface.
 */
export function instanceOfApiUserMarketTransactionsListPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiUserMarketTransactionsListPostRequestFromJSON(json: any): ApiUserMarketTransactionsListPostRequest {
    return ApiUserMarketTransactionsListPostRequestFromJSONTyped(json, false);
}

export function ApiUserMarketTransactionsListPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserMarketTransactionsListPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromDate': !exists(json, 'fromDate') ? undefined : json['fromDate'],
        'toDate': !exists(json, 'toDate') ? undefined : json['toDate'],
    };
}

export function ApiUserMarketTransactionsListPostRequestToJSON(value?: ApiUserMarketTransactionsListPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromDate': value.fromDate,
        'toDate': value.toDate,
    };
}

