/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DistributionGroupListPost200ResponseOneOfListInner
 */
export interface ApiV2DistributionGroupListPost200ResponseOneOfListInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2DistributionGroupListPost200ResponseOneOfListInner
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2DistributionGroupListPost200ResponseOneOfListInner
     */
    groupName: string;
}

/**
 * Check if a given object implements the ApiV2DistributionGroupListPost200ResponseOneOfListInner interface.
 */
export function instanceOfApiV2DistributionGroupListPost200ResponseOneOfListInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupId" in value;
    isInstance = isInstance && "groupName" in value;

    return isInstance;
}

export function ApiV2DistributionGroupListPost200ResponseOneOfListInnerFromJSON(json: any): ApiV2DistributionGroupListPost200ResponseOneOfListInner {
    return ApiV2DistributionGroupListPost200ResponseOneOfListInnerFromJSONTyped(json, false);
}

export function ApiV2DistributionGroupListPost200ResponseOneOfListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DistributionGroupListPost200ResponseOneOfListInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'groupName': json['groupName'],
    };
}

export function ApiV2DistributionGroupListPost200ResponseOneOfListInnerToJSON(value?: ApiV2DistributionGroupListPost200ResponseOneOfListInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupId': value.groupId,
        'groupName': value.groupName,
    };
}

