/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiV2MarketOrderHistoryListPost200ResponseOneOf,
    instanceOfApiV2MarketOrderHistoryListPost200ResponseOneOf,
    ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSON,
    ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSONTyped,
    ApiV2MarketOrderHistoryListPost200ResponseOneOfToJSON,
} from './ApiV2MarketOrderHistoryListPost200ResponseOneOf';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf1,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf1,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf2,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf2,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf3,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf3,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf3';

/**
 * @type ApiV2MarketOrderHistoryListPost200Response
 * 
 * @export
 */
export type ApiV2MarketOrderHistoryListPost200Response = ApiV2MarketOrderHistoryListPost200ResponseOneOf | ApiV2PayPaymentGetPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf3;

export function ApiV2MarketOrderHistoryListPost200ResponseFromJSON(json: any): ApiV2MarketOrderHistoryListPost200Response {
    return ApiV2MarketOrderHistoryListPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2MarketOrderHistoryListPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderHistoryListPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped(json, true) };
}

export function ApiV2MarketOrderHistoryListPost200ResponseToJSON(value?: ApiV2MarketOrderHistoryListPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiV2MarketOrderHistoryListPost200ResponseOneOf(value)) {
        return ApiV2MarketOrderHistoryListPost200ResponseOneOfToJSON(value as ApiV2MarketOrderHistoryListPost200ResponseOneOf);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf1(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf2(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf3(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf3);
    }

    return {};
}

