/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiV2MarketOrderCancelPost200ResponseOneOf,
    instanceOfApiV2MarketOrderCancelPost200ResponseOneOf,
    ApiV2MarketOrderCancelPost200ResponseOneOfFromJSON,
    ApiV2MarketOrderCancelPost200ResponseOneOfFromJSONTyped,
    ApiV2MarketOrderCancelPost200ResponseOneOfToJSON,
} from './ApiV2MarketOrderCancelPost200ResponseOneOf';
import {
    ApiV2MarketOrderCancelPost200ResponseOneOf1,
    instanceOfApiV2MarketOrderCancelPost200ResponseOneOf1,
    ApiV2MarketOrderCancelPost200ResponseOneOf1FromJSON,
    ApiV2MarketOrderCancelPost200ResponseOneOf1FromJSONTyped,
    ApiV2MarketOrderCancelPost200ResponseOneOf1ToJSON,
} from './ApiV2MarketOrderCancelPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf1,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf1,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf2,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf2,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf3,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf3,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf3';

/**
 * @type ApiV2MarketOrderCancelPost200Response
 * 
 * @export
 */
export type ApiV2MarketOrderCancelPost200Response = ApiV2MarketOrderCancelPost200ResponseOneOf | ApiV2MarketOrderCancelPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf3;

export function ApiV2MarketOrderCancelPost200ResponseFromJSON(json: any): ApiV2MarketOrderCancelPost200Response {
    return ApiV2MarketOrderCancelPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2MarketOrderCancelPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderCancelPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiV2MarketOrderCancelPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2MarketOrderCancelPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped(json, true) };
}

export function ApiV2MarketOrderCancelPost200ResponseToJSON(value?: ApiV2MarketOrderCancelPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiV2MarketOrderCancelPost200ResponseOneOf(value)) {
        return ApiV2MarketOrderCancelPost200ResponseOneOfToJSON(value as ApiV2MarketOrderCancelPost200ResponseOneOf);
    }
    if (instanceOfApiV2MarketOrderCancelPost200ResponseOneOf1(value)) {
        return ApiV2MarketOrderCancelPost200ResponseOneOf1ToJSON(value as ApiV2MarketOrderCancelPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf1(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf2(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf3(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf3);
    }

    return {};
}

