/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Payment details
 * @export
 * @interface ApiV2PayPaymentCreatePost200ResponseOneOf
 */
export interface ApiV2PayPaymentCreatePost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayPaymentCreatePost200ResponseOneOf
     */
    result: ApiV2PayPaymentCreatePost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayPaymentCreatePost200ResponseOneOf
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayPaymentCreatePost200ResponseOneOf
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayPaymentCreatePost200ResponseOneOf
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayPaymentCreatePost200ResponseOneOf
     */
    expires: string;
}


/**
 * @export
 */
export const ApiV2PayPaymentCreatePost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2PayPaymentCreatePost200ResponseOneOfResultEnum = typeof ApiV2PayPaymentCreatePost200ResponseOneOfResultEnum[keyof typeof ApiV2PayPaymentCreatePost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2PayPaymentCreatePost200ResponseOneOf interface.
 */
export function instanceOfApiV2PayPaymentCreatePost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "expires" in value;

    return isInstance;
}

export function ApiV2PayPaymentCreatePost200ResponseOneOfFromJSON(json: any): ApiV2PayPaymentCreatePost200ResponseOneOf {
    return ApiV2PayPaymentCreatePost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2PayPaymentCreatePost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2PayPaymentCreatePost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'id': json['id'],
        'state': json['state'],
        'created': json['created'],
        'expires': json['expires'],
    };
}

export function ApiV2PayPaymentCreatePost200ResponseOneOfToJSON(value?: ApiV2PayPaymentCreatePost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'id': value.id,
        'state': value.state,
        'created': value.created,
        'expires': value.expires,
    };
}

