/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2WalletListPostRequest
 */
export interface ApiV2WalletListPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV2WalletListPostRequest
     */
    nonce: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2WalletListPostRequest
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2WalletListPostRequest
     */
    walletKey?: string;
}

/**
 * Check if a given object implements the ApiV2WalletListPostRequest interface.
 */
export function instanceOfApiV2WalletListPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;

    return isInstance;
}

export function ApiV2WalletListPostRequestFromJSON(json: any): ApiV2WalletListPostRequest {
    return ApiV2WalletListPostRequestFromJSONTyped(json, false);
}

export function ApiV2WalletListPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2WalletListPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
        'walletKey': !exists(json, 'walletKey') ? undefined : json['walletKey'],
    };
}

export function ApiV2WalletListPostRequestToJSON(value?: ApiV2WalletListPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
        'walletKey': value.walletKey,
    };
}

