/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Insufficient permission to unassign a label
 * @export
 * @interface ApiV2LabelUnassignPost200ResponseOneOf
 */
export interface ApiV2LabelUnassignPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2LabelUnassignPost200ResponseOneOf
     */
    result: ApiV2LabelUnassignPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiV2LabelUnassignPost200ResponseOneOf
     */
    code: ApiV2LabelUnassignPost200ResponseOneOfCodeEnum;
}


/**
 * @export
 */
export const ApiV2LabelUnassignPost200ResponseOneOfResultEnum = {
    Fail: 'fail'
} as const;
export type ApiV2LabelUnassignPost200ResponseOneOfResultEnum = typeof ApiV2LabelUnassignPost200ResponseOneOfResultEnum[keyof typeof ApiV2LabelUnassignPost200ResponseOneOfResultEnum];

/**
 * @export
 */
export const ApiV2LabelUnassignPost200ResponseOneOfCodeEnum = {
    NUMBER_9000: 9000
} as const;
export type ApiV2LabelUnassignPost200ResponseOneOfCodeEnum = typeof ApiV2LabelUnassignPost200ResponseOneOfCodeEnum[keyof typeof ApiV2LabelUnassignPost200ResponseOneOfCodeEnum];


/**
 * Check if a given object implements the ApiV2LabelUnassignPost200ResponseOneOf interface.
 */
export function instanceOfApiV2LabelUnassignPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ApiV2LabelUnassignPost200ResponseOneOfFromJSON(json: any): ApiV2LabelUnassignPost200ResponseOneOf {
    return ApiV2LabelUnassignPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2LabelUnassignPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2LabelUnassignPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'code': json['code'],
    };
}

export function ApiV2LabelUnassignPost200ResponseOneOfToJSON(value?: ApiV2LabelUnassignPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'code': value.code,
    };
}

