/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2MarketOrderBookPost200ResponseOneOfBidsInner } from './ApiV2MarketOrderBookPost200ResponseOneOfBidsInner';
import {
    ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerFromJSON,
    ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerFromJSONTyped,
    ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerToJSON,
} from './ApiV2MarketOrderBookPost200ResponseOneOfBidsInner';

/**
 * Order canceled successfully
 * @export
 * @interface ApiV2MarketOrderBookPost200ResponseOneOf
 */
export interface ApiV2MarketOrderBookPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderBookPost200ResponseOneOf
     */
    result: ApiV2MarketOrderBookPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {Array<ApiV2MarketOrderBookPost200ResponseOneOfBidsInner>}
     * @memberof ApiV2MarketOrderBookPost200ResponseOneOf
     */
    bids: Array<ApiV2MarketOrderBookPost200ResponseOneOfBidsInner>;
    /**
     * 
     * @type {Array<ApiV2MarketOrderBookPost200ResponseOneOfBidsInner>}
     * @memberof ApiV2MarketOrderBookPost200ResponseOneOf
     */
    asks: Array<ApiV2MarketOrderBookPost200ResponseOneOfBidsInner>;
}


/**
 * @export
 */
export const ApiV2MarketOrderBookPost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2MarketOrderBookPost200ResponseOneOfResultEnum = typeof ApiV2MarketOrderBookPost200ResponseOneOfResultEnum[keyof typeof ApiV2MarketOrderBookPost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2MarketOrderBookPost200ResponseOneOf interface.
 */
export function instanceOfApiV2MarketOrderBookPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "bids" in value;
    isInstance = isInstance && "asks" in value;

    return isInstance;
}

export function ApiV2MarketOrderBookPost200ResponseOneOfFromJSON(json: any): ApiV2MarketOrderBookPost200ResponseOneOf {
    return ApiV2MarketOrderBookPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2MarketOrderBookPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderBookPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'bids': ((json['bids'] as Array<any>).map(ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerFromJSON)),
        'asks': ((json['asks'] as Array<any>).map(ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerFromJSON)),
    };
}

export function ApiV2MarketOrderBookPost200ResponseOneOfToJSON(value?: ApiV2MarketOrderBookPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'bids': ((value.bids as Array<any>).map(ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerToJSON)),
        'asks': ((value.asks as Array<any>).map(ApiV2MarketOrderBookPost200ResponseOneOfBidsInnerToJSON)),
    };
}

