/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2KposRefillPostRequest
 */
export interface ApiV2KposRefillPostRequest {
    /**
     * Unique request identifier, e.g. a timestamp in milliseconds
     * @type {number}
     * @memberof ApiV2KposRefillPostRequest
     */
    nonce: number;
    /**
     * Your public key
     * @type {string}
     * @memberof ApiV2KposRefillPostRequest
     */
    appId: string;
    /**
     * KPOS ID
     * @type {string}
     * @memberof ApiV2KposRefillPostRequest
     */
    kposId: string;
    /**
     * Refill amount
     * @type {string}
     * @memberof ApiV2KposRefillPostRequest
     */
    prize: string;
    /**
     * Number of repetitions (optional)
     * @type {number}
     * @memberof ApiV2KposRefillPostRequest
     */
    repeats?: number;
}

/**
 * Check if a given object implements the ApiV2KposRefillPostRequest interface.
 */
export function instanceOfApiV2KposRefillPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;
    isInstance = isInstance && "kposId" in value;
    isInstance = isInstance && "prize" in value;

    return isInstance;
}

export function ApiV2KposRefillPostRequestFromJSON(json: any): ApiV2KposRefillPostRequest {
    return ApiV2KposRefillPostRequestFromJSONTyped(json, false);
}

export function ApiV2KposRefillPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2KposRefillPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
        'kposId': json['kposId'],
        'prize': json['prize'],
        'repeats': !exists(json, 'repeats') ? undefined : json['repeats'],
    };
}

export function ApiV2KposRefillPostRequestToJSON(value?: ApiV2KposRefillPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
        'kposId': value.kposId,
        'prize': value.prize,
        'repeats': value.repeats,
    };
}

