/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiV2AomStartPost200ResponseOneOf,
    instanceOfApiV2AomStartPost200ResponseOneOf,
    ApiV2AomStartPost200ResponseOneOfFromJSON,
    ApiV2AomStartPost200ResponseOneOfFromJSONTyped,
    ApiV2AomStartPost200ResponseOneOfToJSON,
} from './ApiV2AomStartPost200ResponseOneOf';
import {
    ApiV2LabelAssignPost200ResponseOneOf,
    instanceOfApiV2LabelAssignPost200ResponseOneOf,
    ApiV2LabelAssignPost200ResponseOneOfFromJSON,
    ApiV2LabelAssignPost200ResponseOneOfFromJSONTyped,
    ApiV2LabelAssignPost200ResponseOneOfToJSON,
} from './ApiV2LabelAssignPost200ResponseOneOf';
import {
    ApiV2LabelUnassignPost200ResponseOneOf1,
    instanceOfApiV2LabelUnassignPost200ResponseOneOf1,
    ApiV2LabelUnassignPost200ResponseOneOf1FromJSON,
    ApiV2LabelUnassignPost200ResponseOneOf1FromJSONTyped,
    ApiV2LabelUnassignPost200ResponseOneOf1ToJSON,
} from './ApiV2LabelUnassignPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf1,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf1,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf2,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf2,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf3,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf3,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf3';

/**
 * @type ApiV2LabelAssignPost200Response
 * 
 * @export
 */
export type ApiV2LabelAssignPost200Response = ApiV2AomStartPost200ResponseOneOf | ApiV2LabelAssignPost200ResponseOneOf | ApiV2LabelUnassignPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf3;

export function ApiV2LabelAssignPost200ResponseFromJSON(json: any): ApiV2LabelAssignPost200Response {
    return ApiV2LabelAssignPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2LabelAssignPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2LabelAssignPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiV2AomStartPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2LabelAssignPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2LabelUnassignPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped(json, true) };
}

export function ApiV2LabelAssignPost200ResponseToJSON(value?: ApiV2LabelAssignPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiV2AomStartPost200ResponseOneOf(value)) {
        return ApiV2AomStartPost200ResponseOneOfToJSON(value as ApiV2AomStartPost200ResponseOneOf);
    }
    if (instanceOfApiV2LabelAssignPost200ResponseOneOf(value)) {
        return ApiV2LabelAssignPost200ResponseOneOfToJSON(value as ApiV2LabelAssignPost200ResponseOneOf);
    }
    if (instanceOfApiV2LabelUnassignPost200ResponseOneOf1(value)) {
        return ApiV2LabelUnassignPost200ResponseOneOf1ToJSON(value as ApiV2LabelUnassignPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf1(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf2(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf3(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf3);
    }

    return {};
}

