/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiMarketsPost200ResponseItemsInner } from './ApiMarketsPost200ResponseItemsInner';
import {
    ApiMarketsPost200ResponseItemsInnerFromJSON,
    ApiMarketsPost200ResponseItemsInnerFromJSONTyped,
    ApiMarketsPost200ResponseItemsInnerToJSON,
} from './ApiMarketsPost200ResponseItemsInner';

/**
 * 
 * @export
 * @interface ApiMarketsPost200Response
 */
export interface ApiMarketsPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiMarketsPost200Response
     */
    result: string;
    /**
     * 
     * @type {Array<ApiMarketsPost200ResponseItemsInner>}
     * @memberof ApiMarketsPost200Response
     */
    items: Array<ApiMarketsPost200ResponseItemsInner>;
}

/**
 * Check if a given object implements the ApiMarketsPost200Response interface.
 */
export function instanceOfApiMarketsPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function ApiMarketsPost200ResponseFromJSON(json: any): ApiMarketsPost200Response {
    return ApiMarketsPost200ResponseFromJSONTyped(json, false);
}

export function ApiMarketsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketsPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'items': ((json['items'] as Array<any>).map(ApiMarketsPost200ResponseItemsInnerFromJSON)),
    };
}

export function ApiMarketsPost200ResponseToJSON(value?: ApiMarketsPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'items': ((value.items as Array<any>).map(ApiMarketsPost200ResponseItemsInnerToJSON)),
    };
}

