/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2LabelListPostRequest
 */
export interface ApiV2LabelListPostRequest {
    /**
     * A unique request identifier, e.g. a timestamp in milliseconds
     * @type {number}
     * @memberof ApiV2LabelListPostRequest
     */
    nonce: number;
    /**
     * Your public key
     * @type {string}
     * @memberof ApiV2LabelListPostRequest
     */
    appId: string;
}

/**
 * Check if a given object implements the ApiV2LabelListPostRequest interface.
 */
export function instanceOfApiV2LabelListPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;

    return isInstance;
}

export function ApiV2LabelListPostRequestFromJSON(json: any): ApiV2LabelListPostRequest {
    return ApiV2LabelListPostRequestFromJSONTyped(json, false);
}

export function ApiV2LabelListPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2LabelListPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
    };
}

export function ApiV2LabelListPostRequestToJSON(value?: ApiV2LabelListPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
    };
}

