/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiV2KposBalancesGetPost200ResponseOneOf,
    instanceOfApiV2KposBalancesGetPost200ResponseOneOf,
    ApiV2KposBalancesGetPost200ResponseOneOfFromJSON,
    ApiV2KposBalancesGetPost200ResponseOneOfFromJSONTyped,
    ApiV2KposBalancesGetPost200ResponseOneOfToJSON,
} from './ApiV2KposBalancesGetPost200ResponseOneOf';
import {
    ApiV2KposRefillPost200ResponseOneOf,
    instanceOfApiV2KposRefillPost200ResponseOneOf,
    ApiV2KposRefillPost200ResponseOneOfFromJSON,
    ApiV2KposRefillPost200ResponseOneOfFromJSONTyped,
    ApiV2KposRefillPost200ResponseOneOfToJSON,
} from './ApiV2KposRefillPost200ResponseOneOf';
import {
    ApiV2KposRefillPost200ResponseOneOf1,
    instanceOfApiV2KposRefillPost200ResponseOneOf1,
    ApiV2KposRefillPost200ResponseOneOf1FromJSON,
    ApiV2KposRefillPost200ResponseOneOf1FromJSONTyped,
    ApiV2KposRefillPost200ResponseOneOf1ToJSON,
} from './ApiV2KposRefillPost200ResponseOneOf1';
import {
    ApiV2KposRefillPost200ResponseOneOf2,
    instanceOfApiV2KposRefillPost200ResponseOneOf2,
    ApiV2KposRefillPost200ResponseOneOf2FromJSON,
    ApiV2KposRefillPost200ResponseOneOf2FromJSONTyped,
    ApiV2KposRefillPost200ResponseOneOf2ToJSON,
} from './ApiV2KposRefillPost200ResponseOneOf2';
import {
    ApiV2KposRefillPost200ResponseOneOf3,
    instanceOfApiV2KposRefillPost200ResponseOneOf3,
    ApiV2KposRefillPost200ResponseOneOf3FromJSON,
    ApiV2KposRefillPost200ResponseOneOf3FromJSONTyped,
    ApiV2KposRefillPost200ResponseOneOf3ToJSON,
} from './ApiV2KposRefillPost200ResponseOneOf3';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf1,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf1,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf2,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf2,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf3,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf3,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf3';

/**
 * @type ApiV2KposRefillPost200Response
 * 
 * @export
 */
export type ApiV2KposRefillPost200Response = ApiV2KposBalancesGetPost200ResponseOneOf | ApiV2KposRefillPost200ResponseOneOf | ApiV2KposRefillPost200ResponseOneOf1 | ApiV2KposRefillPost200ResponseOneOf2 | ApiV2KposRefillPost200ResponseOneOf3 | ApiV2PayPaymentGetPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf3;

export function ApiV2KposRefillPost200ResponseFromJSON(json: any): ApiV2KposRefillPost200Response {
    return ApiV2KposRefillPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2KposRefillPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2KposRefillPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiV2KposBalancesGetPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2KposRefillPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2KposRefillPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2KposRefillPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2KposRefillPost200ResponseOneOf3FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped(json, true) };
}

export function ApiV2KposRefillPost200ResponseToJSON(value?: ApiV2KposRefillPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiV2KposBalancesGetPost200ResponseOneOf(value)) {
        return ApiV2KposBalancesGetPost200ResponseOneOfToJSON(value as ApiV2KposBalancesGetPost200ResponseOneOf);
    }
    if (instanceOfApiV2KposRefillPost200ResponseOneOf(value)) {
        return ApiV2KposRefillPost200ResponseOneOfToJSON(value as ApiV2KposRefillPost200ResponseOneOf);
    }
    if (instanceOfApiV2KposRefillPost200ResponseOneOf1(value)) {
        return ApiV2KposRefillPost200ResponseOneOf1ToJSON(value as ApiV2KposRefillPost200ResponseOneOf1);
    }
    if (instanceOfApiV2KposRefillPost200ResponseOneOf2(value)) {
        return ApiV2KposRefillPost200ResponseOneOf2ToJSON(value as ApiV2KposRefillPost200ResponseOneOf2);
    }
    if (instanceOfApiV2KposRefillPost200ResponseOneOf3(value)) {
        return ApiV2KposRefillPost200ResponseOneOf3ToJSON(value as ApiV2KposRefillPost200ResponseOneOf3);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf1(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf2(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf3(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf3);
    }

    return {};
}

