/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2MarketOrderGetPostRequest
 */
export interface ApiV2MarketOrderGetPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV2MarketOrderGetPostRequest
     */
    nonce: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderGetPostRequest
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderGetPostRequest
     */
    orderId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderGetPostRequest
     */
    walletKey?: string;
}

/**
 * Check if a given object implements the ApiV2MarketOrderGetPostRequest interface.
 */
export function instanceOfApiV2MarketOrderGetPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;
    isInstance = isInstance && "orderId" in value;

    return isInstance;
}

export function ApiV2MarketOrderGetPostRequestFromJSON(json: any): ApiV2MarketOrderGetPostRequest {
    return ApiV2MarketOrderGetPostRequestFromJSONTyped(json, false);
}

export function ApiV2MarketOrderGetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderGetPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
        'orderId': json['orderId'],
        'walletKey': !exists(json, 'walletKey') ? undefined : json['walletKey'],
    };
}

export function ApiV2MarketOrderGetPostRequestToJSON(value?: ApiV2MarketOrderGetPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
        'orderId': value.orderId,
        'walletKey': value.walletKey,
    };
}

