/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Order book
 * @export
 * @interface ApiV2MarketOrderbookRawGet200Response
 */
export interface ApiV2MarketOrderbookRawGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2MarketOrderbookRawGet200Response
     */
    timestamp: number;
    /**
     * 
     * @type {object}
     * @memberof ApiV2MarketOrderbookRawGet200Response
     */
    bids: object;
    /**
     * 
     * @type {object}
     * @memberof ApiV2MarketOrderbookRawGet200Response
     */
    asks: object;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderbookRawGet200Response
     */
    tickerId: string;
}

/**
 * Check if a given object implements the ApiV2MarketOrderbookRawGet200Response interface.
 */
export function instanceOfApiV2MarketOrderbookRawGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "bids" in value;
    isInstance = isInstance && "asks" in value;
    isInstance = isInstance && "tickerId" in value;

    return isInstance;
}

export function ApiV2MarketOrderbookRawGet200ResponseFromJSON(json: any): ApiV2MarketOrderbookRawGet200Response {
    return ApiV2MarketOrderbookRawGet200ResponseFromJSONTyped(json, false);
}

export function ApiV2MarketOrderbookRawGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderbookRawGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'bids': json['bids'],
        'asks': json['asks'],
        'tickerId': json['ticker_id'],
    };
}

export function ApiV2MarketOrderbookRawGet200ResponseToJSON(value?: ApiV2MarketOrderbookRawGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'bids': value.bids,
        'asks': value.asks,
        'ticker_id': value.tickerId,
    };
}

