/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Transfers failed
 * @export
 * @interface ApiV2AomClosePost200ResponseOneOf2
 */
export interface ApiV2AomClosePost200ResponseOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomClosePost200ResponseOneOf2
     */
    result: ApiV2AomClosePost200ResponseOneOf2ResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AomClosePost200ResponseOneOf2
     */
    code: ApiV2AomClosePost200ResponseOneOf2CodeEnum;
}


/**
 * @export
 */
export const ApiV2AomClosePost200ResponseOneOf2ResultEnum = {
    Fail: 'fail'
} as const;
export type ApiV2AomClosePost200ResponseOneOf2ResultEnum = typeof ApiV2AomClosePost200ResponseOneOf2ResultEnum[keyof typeof ApiV2AomClosePost200ResponseOneOf2ResultEnum];

/**
 * @export
 */
export const ApiV2AomClosePost200ResponseOneOf2CodeEnum = {
    NUMBER_9001: 9001
} as const;
export type ApiV2AomClosePost200ResponseOneOf2CodeEnum = typeof ApiV2AomClosePost200ResponseOneOf2CodeEnum[keyof typeof ApiV2AomClosePost200ResponseOneOf2CodeEnum];


/**
 * Check if a given object implements the ApiV2AomClosePost200ResponseOneOf2 interface.
 */
export function instanceOfApiV2AomClosePost200ResponseOneOf2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ApiV2AomClosePost200ResponseOneOf2FromJSON(json: any): ApiV2AomClosePost200ResponseOneOf2 {
    return ApiV2AomClosePost200ResponseOneOf2FromJSONTyped(json, false);
}

export function ApiV2AomClosePost200ResponseOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomClosePost200ResponseOneOf2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'code': json['code'],
    };
}

export function ApiV2AomClosePost200ResponseOneOf2ToJSON(value?: ApiV2AomClosePost200ResponseOneOf2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'code': value.code,
    };
}

