/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2MarketOrderListPost200ResponseOneOfOrdersInner } from './ApiV2MarketOrderListPost200ResponseOneOfOrdersInner';
import {
    ApiV2MarketOrderListPost200ResponseOneOfOrdersInnerFromJSON,
    ApiV2MarketOrderListPost200ResponseOneOfOrdersInnerFromJSONTyped,
    ApiV2MarketOrderListPost200ResponseOneOfOrdersInnerToJSON,
} from './ApiV2MarketOrderListPost200ResponseOneOfOrdersInner';

/**
 * List of active orders
 * @export
 * @interface ApiV2MarketOrderListPost200ResponseOneOf
 */
export interface ApiV2MarketOrderListPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderListPost200ResponseOneOf
     */
    result: ApiV2MarketOrderListPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {Array<ApiV2MarketOrderListPost200ResponseOneOfOrdersInner>}
     * @memberof ApiV2MarketOrderListPost200ResponseOneOf
     */
    orders: Array<ApiV2MarketOrderListPost200ResponseOneOfOrdersInner>;
}


/**
 * @export
 */
export const ApiV2MarketOrderListPost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2MarketOrderListPost200ResponseOneOfResultEnum = typeof ApiV2MarketOrderListPost200ResponseOneOfResultEnum[keyof typeof ApiV2MarketOrderListPost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2MarketOrderListPost200ResponseOneOf interface.
 */
export function instanceOfApiV2MarketOrderListPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "orders" in value;

    return isInstance;
}

export function ApiV2MarketOrderListPost200ResponseOneOfFromJSON(json: any): ApiV2MarketOrderListPost200ResponseOneOf {
    return ApiV2MarketOrderListPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2MarketOrderListPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderListPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'orders': ((json['orders'] as Array<any>).map(ApiV2MarketOrderListPost200ResponseOneOfOrdersInnerFromJSON)),
    };
}

export function ApiV2MarketOrderListPost200ResponseOneOfToJSON(value?: ApiV2MarketOrderListPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'orders': ((value.orders as Array<any>).map(ApiV2MarketOrderListPost200ResponseOneOfOrdersInnerToJSON)),
    };
}

