/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2MarketOrderCreatePostRequest
 */
export interface ApiV2MarketOrderCreatePostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    nonce: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    quantity: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    valueLimit?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    type: ApiV2MarketOrderCreatePostRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderCreatePostRequest
     */
    market: string;
}


/**
 * @export
 */
export const ApiV2MarketOrderCreatePostRequestTypeEnum = {
    Bid: 'BID',
    Ask: 'ASK'
} as const;
export type ApiV2MarketOrderCreatePostRequestTypeEnum = typeof ApiV2MarketOrderCreatePostRequestTypeEnum[keyof typeof ApiV2MarketOrderCreatePostRequestTypeEnum];


/**
 * Check if a given object implements the ApiV2MarketOrderCreatePostRequest interface.
 */
export function instanceOfApiV2MarketOrderCreatePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "market" in value;

    return isInstance;
}

export function ApiV2MarketOrderCreatePostRequestFromJSON(json: any): ApiV2MarketOrderCreatePostRequest {
    return ApiV2MarketOrderCreatePostRequestFromJSONTyped(json, false);
}

export function ApiV2MarketOrderCreatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderCreatePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
        'quantity': json['quantity'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'valueLimit': !exists(json, 'valueLimit') ? undefined : json['valueLimit'],
        'type': json['type'],
        'market': json['market'],
    };
}

export function ApiV2MarketOrderCreatePostRequestToJSON(value?: ApiV2MarketOrderCreatePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
        'quantity': value.quantity,
        'price': value.price,
        'valueLimit': value.valueLimit,
        'type': value.type,
        'market': value.market,
    };
}

