/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2MarketDepthGet200ResponseBidsInner } from './ApiV2MarketDepthGet200ResponseBidsInner';
import {
    ApiV2MarketDepthGet200ResponseBidsInnerFromJSON,
    ApiV2MarketDepthGet200ResponseBidsInnerFromJSONTyped,
    ApiV2MarketDepthGet200ResponseBidsInnerToJSON,
} from './ApiV2MarketDepthGet200ResponseBidsInner';

/**
 * Order book
 * @export
 * @interface ApiV2MarketDepthGet200Response
 */
export interface ApiV2MarketDepthGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketDepthGet200Response
     */
    timestamp: string;
    /**
     * 
     * @type {Array<ApiV2MarketDepthGet200ResponseBidsInner>}
     * @memberof ApiV2MarketDepthGet200Response
     */
    bids: Array<ApiV2MarketDepthGet200ResponseBidsInner>;
    /**
     * 
     * @type {Array<ApiV2MarketDepthGet200ResponseBidsInner>}
     * @memberof ApiV2MarketDepthGet200Response
     */
    asks: Array<ApiV2MarketDepthGet200ResponseBidsInner>;
}

/**
 * Check if a given object implements the ApiV2MarketDepthGet200Response interface.
 */
export function instanceOfApiV2MarketDepthGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "bids" in value;
    isInstance = isInstance && "asks" in value;

    return isInstance;
}

export function ApiV2MarketDepthGet200ResponseFromJSON(json: any): ApiV2MarketDepthGet200Response {
    return ApiV2MarketDepthGet200ResponseFromJSONTyped(json, false);
}

export function ApiV2MarketDepthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketDepthGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'bids': ((json['bids'] as Array<any>).map(ApiV2MarketDepthGet200ResponseBidsInnerFromJSON)),
        'asks': ((json['asks'] as Array<any>).map(ApiV2MarketDepthGet200ResponseBidsInnerFromJSON)),
    };
}

export function ApiV2MarketDepthGet200ResponseToJSON(value?: ApiV2MarketDepthGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'bids': ((value.bids as Array<any>).map(ApiV2MarketDepthGet200ResponseBidsInnerToJSON)),
        'asks': ((value.asks as Array<any>).map(ApiV2MarketDepthGet200ResponseBidsInnerToJSON)),
    };
}

