/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2AomListPost200ResponseOneOfListInner } from './ApiV2AomListPost200ResponseOneOfListInner';
import {
    ApiV2AomListPost200ResponseOneOfListInnerFromJSON,
    ApiV2AomListPost200ResponseOneOfListInnerFromJSONTyped,
    ApiV2AomListPost200ResponseOneOfListInnerToJSON,
} from './ApiV2AomListPost200ResponseOneOfListInner';

/**
 * 
 * @export
 * @interface ApiV2AomListPost200ResponseOneOf
 */
export interface ApiV2AomListPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomListPost200ResponseOneOf
     */
    result: ApiV2AomListPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {Array<ApiV2AomListPost200ResponseOneOfListInner>}
     * @memberof ApiV2AomListPost200ResponseOneOf
     */
    list: Array<ApiV2AomListPost200ResponseOneOfListInner>;
}


/**
 * @export
 */
export const ApiV2AomListPost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2AomListPost200ResponseOneOfResultEnum = typeof ApiV2AomListPost200ResponseOneOfResultEnum[keyof typeof ApiV2AomListPost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2AomListPost200ResponseOneOf interface.
 */
export function instanceOfApiV2AomListPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "list" in value;

    return isInstance;
}

export function ApiV2AomListPost200ResponseOneOfFromJSON(json: any): ApiV2AomListPost200ResponseOneOf {
    return ApiV2AomListPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2AomListPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomListPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'list': ((json['list'] as Array<any>).map(ApiV2AomListPost200ResponseOneOfListInnerFromJSON)),
    };
}

export function ApiV2AomListPost200ResponseOneOfToJSON(value?: ApiV2AomListPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'list': ((value.list as Array<any>).map(ApiV2AomListPost200ResponseOneOfListInnerToJSON)),
    };
}

