/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AomUpdatePostRequest
 */
export interface ApiV2AomUpdatePostRequest {
    /**
     * Unique request identifier, e.g. a timestamp in milliseconds
     * @type {number}
     * @memberof ApiV2AomUpdatePostRequest
     */
    nonce: number;
    /**
     * Your public key
     * @type {string}
     * @memberof ApiV2AomUpdatePostRequest
     */
    appId: string;
    /**
     * Order maker ID.
     * @type {string}
     * @memberof ApiV2AomUpdatePostRequest
     */
    aomId: string;
    /**
     * Minimum order amount, e.g. '12.1234'. Decimal precision depends on currency (up to 18 decimal places).
     * @type {string}
     * @memberof ApiV2AomUpdatePostRequest
     */
    minAmount: string;
    /**
     * Maximum order amount. May be equal to or greater than minimum amount.
     * @type {string}
     * @memberof ApiV2AomUpdatePostRequest
     */
    maxAmount: string;
    /**
     * Minimum delay between orders in seconds (integer).
     * @type {number}
     * @memberof ApiV2AomUpdatePostRequest
     */
    minDelay: number;
    /**
     * Maximum delay between orders in seconds (integer). May be equal to or greater than the minimum delay.
     * @type {number}
     * @memberof ApiV2AomUpdatePostRequest
     */
    maxDelay: number;
}

/**
 * Check if a given object implements the ApiV2AomUpdatePostRequest interface.
 */
export function instanceOfApiV2AomUpdatePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "appId" in value;
    isInstance = isInstance && "aomId" in value;
    isInstance = isInstance && "minAmount" in value;
    isInstance = isInstance && "maxAmount" in value;
    isInstance = isInstance && "minDelay" in value;
    isInstance = isInstance && "maxDelay" in value;

    return isInstance;
}

export function ApiV2AomUpdatePostRequestFromJSON(json: any): ApiV2AomUpdatePostRequest {
    return ApiV2AomUpdatePostRequestFromJSONTyped(json, false);
}

export function ApiV2AomUpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomUpdatePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'appId': json['appId'],
        'aomId': json['aomId'],
        'minAmount': json['minAmount'],
        'maxAmount': json['maxAmount'],
        'minDelay': json['minDelay'],
        'maxDelay': json['maxDelay'],
    };
}

export function ApiV2AomUpdatePostRequestToJSON(value?: ApiV2AomUpdatePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
        'appId': value.appId,
        'aomId': value.aomId,
        'minAmount': value.minAmount,
        'maxAmount': value.maxAmount,
        'minDelay': value.minDelay,
        'maxDelay': value.maxDelay,
    };
}

