/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Transferred amounts, e.g. {BTC:"0.02", USDT:"200.5"}
 * @export
 * @interface ApiV2AomClosePost200ResponseOneOf
 */
export interface ApiV2AomClosePost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomClosePost200ResponseOneOf
     */
    result: ApiV2AomClosePost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {object}
     * @memberof ApiV2AomClosePost200ResponseOneOf
     */
    transferred: object;
}


/**
 * @export
 */
export const ApiV2AomClosePost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2AomClosePost200ResponseOneOfResultEnum = typeof ApiV2AomClosePost200ResponseOneOfResultEnum[keyof typeof ApiV2AomClosePost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2AomClosePost200ResponseOneOf interface.
 */
export function instanceOfApiV2AomClosePost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "transferred" in value;

    return isInstance;
}

export function ApiV2AomClosePost200ResponseOneOfFromJSON(json: any): ApiV2AomClosePost200ResponseOneOf {
    return ApiV2AomClosePost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2AomClosePost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomClosePost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'transferred': json['transferred'],
    };
}

export function ApiV2AomClosePost200ResponseOneOfToJSON(value?: ApiV2AomClosePost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'transferred': value.transferred,
    };
}

