/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInner } from './ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInner';
import {
    ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInnerFromJSON,
    ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInnerFromJSONTyped,
    ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInnerToJSON,
} from './ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInner';

/**
 * List of fulfilled or canceled orders
 * @export
 * @interface ApiV2MarketOrderHistoryListPost200ResponseOneOf
 */
export interface ApiV2MarketOrderHistoryListPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketOrderHistoryListPost200ResponseOneOf
     */
    result: ApiV2MarketOrderHistoryListPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {Array<ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInner>}
     * @memberof ApiV2MarketOrderHistoryListPost200ResponseOneOf
     */
    orders: Array<ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInner>;
}


/**
 * @export
 */
export const ApiV2MarketOrderHistoryListPost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2MarketOrderHistoryListPost200ResponseOneOfResultEnum = typeof ApiV2MarketOrderHistoryListPost200ResponseOneOfResultEnum[keyof typeof ApiV2MarketOrderHistoryListPost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2MarketOrderHistoryListPost200ResponseOneOf interface.
 */
export function instanceOfApiV2MarketOrderHistoryListPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "orders" in value;

    return isInstance;
}

export function ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSON(json: any): ApiV2MarketOrderHistoryListPost200ResponseOneOf {
    return ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2MarketOrderHistoryListPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketOrderHistoryListPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'orders': ((json['orders'] as Array<any>).map(ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInnerFromJSON)),
    };
}

export function ApiV2MarketOrderHistoryListPost200ResponseOneOfToJSON(value?: ApiV2MarketOrderHistoryListPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'orders': ((value.orders as Array<any>).map(ApiV2MarketOrderHistoryListPost200ResponseOneOfOrdersInnerToJSON)),
    };
}

