/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AomGetPost200ResponseOneOf
 */
export interface ApiV2AomGetPost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    result: ApiV2AomGetPost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    marketId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    minAmount: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    maxAmount: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    minDelay: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    maxDelay: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    created: string;
    /**
     * 
     * @type {object}
     * @memberof ApiV2AomGetPost200ResponseOneOf
     */
    balances: object;
}


/**
 * @export
 */
export const ApiV2AomGetPost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2AomGetPost200ResponseOneOfResultEnum = typeof ApiV2AomGetPost200ResponseOneOfResultEnum[keyof typeof ApiV2AomGetPost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2AomGetPost200ResponseOneOf interface.
 */
export function instanceOfApiV2AomGetPost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "marketId" in value;
    isInstance = isInstance && "currency" in value;
    isInstance = isInstance && "minAmount" in value;
    isInstance = isInstance && "maxAmount" in value;
    isInstance = isInstance && "minDelay" in value;
    isInstance = isInstance && "maxDelay" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "balances" in value;

    return isInstance;
}

export function ApiV2AomGetPost200ResponseOneOfFromJSON(json: any): ApiV2AomGetPost200ResponseOneOf {
    return ApiV2AomGetPost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2AomGetPost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomGetPost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'marketId': json['marketId'],
        'currency': json['currency'],
        'minAmount': json['minAmount'],
        'maxAmount': json['maxAmount'],
        'minDelay': json['minDelay'],
        'maxDelay': json['maxDelay'],
        'state': json['state'],
        'created': json['created'],
        'balances': json['balances'],
    };
}

export function ApiV2AomGetPost200ResponseOneOfToJSON(value?: ApiV2AomGetPost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'marketId': value.marketId,
        'currency': value.currency,
        'minAmount': value.minAmount,
        'maxAmount': value.maxAmount,
        'minDelay': value.minDelay,
        'maxDelay': value.maxDelay,
        'state': value.state,
        'created': value.created,
        'balances': value.balances,
    };
}

