/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AomCreatePost200ResponseOneOf
 */
export interface ApiV2AomCreatePost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomCreatePost200ResponseOneOf
     */
    result: ApiV2AomCreatePost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AomCreatePost200ResponseOneOf
     */
    aomId: string;
}


/**
 * @export
 */
export const ApiV2AomCreatePost200ResponseOneOfResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2AomCreatePost200ResponseOneOfResultEnum = typeof ApiV2AomCreatePost200ResponseOneOfResultEnum[keyof typeof ApiV2AomCreatePost200ResponseOneOfResultEnum];


/**
 * Check if a given object implements the ApiV2AomCreatePost200ResponseOneOf interface.
 */
export function instanceOfApiV2AomCreatePost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "aomId" in value;

    return isInstance;
}

export function ApiV2AomCreatePost200ResponseOneOfFromJSON(json: any): ApiV2AomCreatePost200ResponseOneOf {
    return ApiV2AomCreatePost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2AomCreatePost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomCreatePost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'aomId': json['aomId'],
    };
}

export function ApiV2AomCreatePost200ResponseOneOfToJSON(value?: ApiV2AomCreatePost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'aomId': value.aomId,
    };
}

