/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Too many recipients or empty distribution
 * @export
 * @interface ApiV2DistributionCreatePost200ResponseOneOf
 */
export interface ApiV2DistributionCreatePost200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2DistributionCreatePost200ResponseOneOf
     */
    result: ApiV2DistributionCreatePost200ResponseOneOfResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DistributionCreatePost200ResponseOneOf
     */
    code: ApiV2DistributionCreatePost200ResponseOneOfCodeEnum;
}


/**
 * @export
 */
export const ApiV2DistributionCreatePost200ResponseOneOfResultEnum = {
    Fail: 'fail'
} as const;
export type ApiV2DistributionCreatePost200ResponseOneOfResultEnum = typeof ApiV2DistributionCreatePost200ResponseOneOfResultEnum[keyof typeof ApiV2DistributionCreatePost200ResponseOneOfResultEnum];

/**
 * @export
 */
export const ApiV2DistributionCreatePost200ResponseOneOfCodeEnum = {
    NUMBER_9000: 9000
} as const;
export type ApiV2DistributionCreatePost200ResponseOneOfCodeEnum = typeof ApiV2DistributionCreatePost200ResponseOneOfCodeEnum[keyof typeof ApiV2DistributionCreatePost200ResponseOneOfCodeEnum];


/**
 * Check if a given object implements the ApiV2DistributionCreatePost200ResponseOneOf interface.
 */
export function instanceOfApiV2DistributionCreatePost200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ApiV2DistributionCreatePost200ResponseOneOfFromJSON(json: any): ApiV2DistributionCreatePost200ResponseOneOf {
    return ApiV2DistributionCreatePost200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2DistributionCreatePost200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DistributionCreatePost200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'code': json['code'],
    };
}

export function ApiV2DistributionCreatePost200ResponseOneOfToJSON(value?: ApiV2DistributionCreatePost200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'code': value.code,
    };
}

