/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DistributionCreatePostRequestDistributionInner
 */
export interface ApiV2DistributionCreatePostRequestDistributionInner {
    /**
     * App user ID.
     * @type {string}
     * @memberof ApiV2DistributionCreatePostRequestDistributionInner
     */
    appUserId: string;
    /**
     * Quantity of tokens.
     * @type {string}
     * @memberof ApiV2DistributionCreatePostRequestDistributionInner
     */
    quantity: string;
}

/**
 * Check if a given object implements the ApiV2DistributionCreatePostRequestDistributionInner interface.
 */
export function instanceOfApiV2DistributionCreatePostRequestDistributionInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appUserId" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function ApiV2DistributionCreatePostRequestDistributionInnerFromJSON(json: any): ApiV2DistributionCreatePostRequestDistributionInner {
    return ApiV2DistributionCreatePostRequestDistributionInnerFromJSONTyped(json, false);
}

export function ApiV2DistributionCreatePostRequestDistributionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DistributionCreatePostRequestDistributionInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appUserId': json['appUserId'],
        'quantity': json['quantity'],
    };
}

export function ApiV2DistributionCreatePostRequestDistributionInnerToJSON(value?: ApiV2DistributionCreatePostRequestDistributionInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appUserId': value.appUserId,
        'quantity': value.quantity,
    };
}

