/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Market changes
 * @export
 * @interface ApiV2MarketChangesGet200ResponseOneOf
 */
export interface ApiV2MarketChangesGet200ResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    minPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    maxPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    highestBid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    lowestAsk?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    volume?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    volume24?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    quantityVolume24?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    weeklyVolume?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    monthlyVolume?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    change?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2MarketChangesGet200ResponseOneOf
     */
    changeQuantity?: string;
}

/**
 * Check if a given object implements the ApiV2MarketChangesGet200ResponseOneOf interface.
 */
export function instanceOfApiV2MarketChangesGet200ResponseOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function ApiV2MarketChangesGet200ResponseOneOfFromJSON(json: any): ApiV2MarketChangesGet200ResponseOneOf {
    return ApiV2MarketChangesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiV2MarketChangesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2MarketChangesGet200ResponseOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'minPrice': !exists(json, 'minPrice') ? undefined : json['minPrice'],
        'maxPrice': !exists(json, 'maxPrice') ? undefined : json['maxPrice'],
        'highestBid': !exists(json, 'highestBid') ? undefined : json['highestBid'],
        'lowestAsk': !exists(json, 'lowestAsk') ? undefined : json['lowestAsk'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'volume24': !exists(json, 'volume24') ? undefined : json['volume24'],
        'quantityVolume24': !exists(json, 'quantityVolume24') ? undefined : json['quantityVolume24'],
        'weeklyVolume': !exists(json, 'weeklyVolume') ? undefined : json['weeklyVolume'],
        'monthlyVolume': !exists(json, 'monthlyVolume') ? undefined : json['monthlyVolume'],
        'change': !exists(json, 'change') ? undefined : json['change'],
        'changeQuantity': !exists(json, 'changeQuantity') ? undefined : json['changeQuantity'],
    };
}

export function ApiV2MarketChangesGet200ResponseOneOfToJSON(value?: ApiV2MarketChangesGet200ResponseOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'price': value.price,
        'minPrice': value.minPrice,
        'maxPrice': value.maxPrice,
        'highestBid': value.highestBid,
        'lowestAsk': value.lowestAsk,
        'volume': value.volume,
        'volume24': value.volume24,
        'quantityVolume24': value.quantityVolume24,
        'weeklyVolume': value.weeklyVolume,
        'monthlyVolume': value.monthlyVolume,
        'change': value.change,
        'changeQuantity': value.changeQuantity,
    };
}

