/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner
 */
export interface ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner
     */
    address?: string;
}

/**
 * Check if a given object implements the ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner interface.
 */
export function instanceOfApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "network" in value;

    return isInstance;
}

export function ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInnerFromJSON(json: any): ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner {
    return ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInnerFromJSONTyped(json, false);
}

export function ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInnerToJSON(value?: ApiV2WalletListPost200ResponseOneOfWalletsInnerAddressesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'type': value.type,
        'address': value.address,
    };
}

