/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApiV2AomGetPost200ResponseOneOf1,
    instanceOfApiV2AomGetPost200ResponseOneOf1,
    ApiV2AomGetPost200ResponseOneOf1FromJSON,
    ApiV2AomGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2AomGetPost200ResponseOneOf1ToJSON,
} from './ApiV2AomGetPost200ResponseOneOf1';
import {
    ApiV2AomWithdrawPost200ResponseOneOf,
    instanceOfApiV2AomWithdrawPost200ResponseOneOf,
    ApiV2AomWithdrawPost200ResponseOneOfFromJSON,
    ApiV2AomWithdrawPost200ResponseOneOfFromJSONTyped,
    ApiV2AomWithdrawPost200ResponseOneOfToJSON,
} from './ApiV2AomWithdrawPost200ResponseOneOf';
import {
    ApiV2AomWithdrawPost200ResponseOneOf1,
    instanceOfApiV2AomWithdrawPost200ResponseOneOf1,
    ApiV2AomWithdrawPost200ResponseOneOf1FromJSON,
    ApiV2AomWithdrawPost200ResponseOneOf1FromJSONTyped,
    ApiV2AomWithdrawPost200ResponseOneOf1ToJSON,
} from './ApiV2AomWithdrawPost200ResponseOneOf1';
import {
    ApiV2AomWithdrawPost200ResponseOneOf2,
    instanceOfApiV2AomWithdrawPost200ResponseOneOf2,
    ApiV2AomWithdrawPost200ResponseOneOf2FromJSON,
    ApiV2AomWithdrawPost200ResponseOneOf2FromJSONTyped,
    ApiV2AomWithdrawPost200ResponseOneOf2ToJSON,
} from './ApiV2AomWithdrawPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf1,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf1,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf1';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf2,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf2,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf2';
import {
    ApiV2PayPaymentGetPost200ResponseOneOf3,
    instanceOfApiV2PayPaymentGetPost200ResponseOneOf3,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSON,
    ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped,
    ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON,
} from './ApiV2PayPaymentGetPost200ResponseOneOf3';

/**
 * @type ApiV2AomWithdrawPost200Response
 * 
 * @export
 */
export type ApiV2AomWithdrawPost200Response = ApiV2AomGetPost200ResponseOneOf1 | ApiV2AomWithdrawPost200ResponseOneOf | ApiV2AomWithdrawPost200ResponseOneOf1 | ApiV2AomWithdrawPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf1 | ApiV2PayPaymentGetPost200ResponseOneOf2 | ApiV2PayPaymentGetPost200ResponseOneOf3;

export function ApiV2AomWithdrawPost200ResponseFromJSON(json: any): ApiV2AomWithdrawPost200Response {
    return ApiV2AomWithdrawPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AomWithdrawPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AomWithdrawPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ApiV2AomGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2AomWithdrawPost200ResponseOneOfFromJSONTyped(json, true), ...ApiV2AomWithdrawPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2AomWithdrawPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf1FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf2FromJSONTyped(json, true), ...ApiV2PayPaymentGetPost200ResponseOneOf3FromJSONTyped(json, true) };
}

export function ApiV2AomWithdrawPost200ResponseToJSON(value?: ApiV2AomWithdrawPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfApiV2AomGetPost200ResponseOneOf1(value)) {
        return ApiV2AomGetPost200ResponseOneOf1ToJSON(value as ApiV2AomGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2AomWithdrawPost200ResponseOneOf(value)) {
        return ApiV2AomWithdrawPost200ResponseOneOfToJSON(value as ApiV2AomWithdrawPost200ResponseOneOf);
    }
    if (instanceOfApiV2AomWithdrawPost200ResponseOneOf1(value)) {
        return ApiV2AomWithdrawPost200ResponseOneOf1ToJSON(value as ApiV2AomWithdrawPost200ResponseOneOf1);
    }
    if (instanceOfApiV2AomWithdrawPost200ResponseOneOf2(value)) {
        return ApiV2AomWithdrawPost200ResponseOneOf2ToJSON(value as ApiV2AomWithdrawPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf1(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf1ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf1);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf2(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf2ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf2);
    }
    if (instanceOfApiV2PayPaymentGetPost200ResponseOneOf3(value)) {
        return ApiV2PayPaymentGetPost200ResponseOneOf3ToJSON(value as ApiV2PayPaymentGetPost200ResponseOneOf3);
    }

    return {};
}

