/* tslint:disable */
/* eslint-disable */
/**
 * Kanga Exchange API
 * API documentation generated from Kanga Exchange source code.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanga.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV2PayCurrenciesListGet200ResponseListInner } from './ApiV2PayCurrenciesListGet200ResponseListInner';
import {
    ApiV2PayCurrenciesListGet200ResponseListInnerFromJSON,
    ApiV2PayCurrenciesListGet200ResponseListInnerFromJSONTyped,
    ApiV2PayCurrenciesListGet200ResponseListInnerToJSON,
} from './ApiV2PayCurrenciesListGet200ResponseListInner';

/**
 * 
 * @export
 * @interface ApiV2PayCurrenciesListGet200Response
 */
export interface ApiV2PayCurrenciesListGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2PayCurrenciesListGet200Response
     */
    result: ApiV2PayCurrenciesListGet200ResponseResultEnum;
    /**
     * 
     * @type {Array<ApiV2PayCurrenciesListGet200ResponseListInner>}
     * @memberof ApiV2PayCurrenciesListGet200Response
     */
    list: Array<ApiV2PayCurrenciesListGet200ResponseListInner>;
}


/**
 * @export
 */
export const ApiV2PayCurrenciesListGet200ResponseResultEnum = {
    Ok: 'ok'
} as const;
export type ApiV2PayCurrenciesListGet200ResponseResultEnum = typeof ApiV2PayCurrenciesListGet200ResponseResultEnum[keyof typeof ApiV2PayCurrenciesListGet200ResponseResultEnum];


/**
 * Check if a given object implements the ApiV2PayCurrenciesListGet200Response interface.
 */
export function instanceOfApiV2PayCurrenciesListGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "list" in value;

    return isInstance;
}

export function ApiV2PayCurrenciesListGet200ResponseFromJSON(json: any): ApiV2PayCurrenciesListGet200Response {
    return ApiV2PayCurrenciesListGet200ResponseFromJSONTyped(json, false);
}

export function ApiV2PayCurrenciesListGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2PayCurrenciesListGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'list': ((json['list'] as Array<any>).map(ApiV2PayCurrenciesListGet200ResponseListInnerFromJSON)),
    };
}

export function ApiV2PayCurrenciesListGet200ResponseToJSON(value?: ApiV2PayCurrenciesListGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'list': ((value.list as Array<any>).map(ApiV2PayCurrenciesListGet200ResponseListInnerToJSON)),
    };
}

